/* Insert Values to the tables */ 
INSERT INTO country 
VALUES      ('Afghanistan'), 
            ('Albania'), 
            ('Algeria'), 
            ('Andorra'), 
            ('Australia'), 
            ('Austria'), 
            ('Brazil'), 
            ('Bangladesh'), 
            ('China'), 
            ('Chile'), 
            ('Denmark'), 
            ('Egypt'), 
            ('Ethiopia'), 
            ('France'), 
            ('Finland'), 
            ('Germany'), 
            ('Georgia'), 
            ('Greece'), 
            ('Hong Kong'), 
            ('Hungary'), 
            ('India'), 
            ('Ireland'), 
            ('Japan'), 
            ('Kuwait'), 
            ('Kenya'), 
            ('Luxembourg'), 
            ('Mexico'), 
            ('Nepal'), 
            ('Oman'), 
            ('Poland'), 
            ('Qatar'), 
            ('Russia'), 
            ('South Africa'), 
            ('Switzerland'), 
            ('Syria'), 
            ('Thailand'), 
            ('United States'), 
            ('Uganda'), 
            ('Vietnam'), 
            ('Yemen'), 
            ('Zimbabwe'); 

INSERT INTO state 
VALUES      (1, 
             'Badakhshan'), 
            (1, 
             'Badghis'), 
            (1, 
             'Baghlan'), 
            (2, 
             'Berat'), 
            (2, 
             'Diber'), 
            (2, 
             'Durres'), 
            (3, 
             'Adrar'), 
            (3, 
             'Blida'), 
            (3, 
             'Tipaza'), 
            (4, 
             'Canillo'), 
            (4, 
             'Ordino'), 
            (5, 
             'Tasmania'), 
            (5, 
             'Victoria'), 
            (6, 
             'Burgenland'), 
            (6, 
             'Tirol'), 
            (7, 
             'Bahia'), 
            (7, 
             'Roraima'), 
            (8, 
             'Dhaka'), 
            (9, 
             'Jilin'), 
            (10, 
             'Atacama'), 
            (11, 
             'Capital'), 
            (12, 
             'Suhaj'), 
            (13, 
             'Tigray'), 
            (14, 
             'Auvergne'), 
            (15, 
             'South Savo'), 
            (16, 
             'Bremen'), 
            (17, 
             'Ajaria'), 
            (18, 
             'Crete'), 
            (19, 
             'Eastern District'), 
            (20, 
             'BaranyaMegye'), 
            (21, 
             'Kerala'), 
            (22, 
             'Cavan'), 
            (23, 
             'Akita'), 
            (24, 
             'Hawalli'), 
            (25, 
             'Central'), 
            (26, 
             'Diekirch'), 
            (27, 
             'Colima'), 
            (28, 
             'Eastern'), 
            (29, 
             'Dhofar'), 
            (30, 
             'Lodzkie'), 
            (31, 
             'Al Khawr'), 
            (32, 
             'Altay'), 
            (33, 
             'Free State'), 
            (34, 
             'Bern'), 
            (35, 
             'Idlib'), 
            (36, 
             'Chai Nat'), 
            (37, 
             'Alaska'), 
            (37, 
             'Texas'), 
            (37, 
             'New York'), 
            (37, 
             'California'), 
            (38, 
             'Abim'), 
            (39, 
             'Bac Can'), 
            (40, 
             'Ataq'), 
            (41, 
             'Bulawayo'), 
            (0, 
             ' '), 
            (37, 
             'New Jersey'); 

/* Approach1 to deal with missing identity */ 
UPDATE state 
SET    country_id = 37, 
       state_name = 'New Jersey' 
WHERE  state_id = 55; 

DELETE FROM state 
WHERE  state_id = 56; 

/* Approach2 to deal with missing identity */ 
DBCC checkident (city, reseed, 0) 

INSERT INTO city 
VALUES      (1, 
             'Jurm'), 
            (2, 
             'Abbakhsh'), 
            (3, 
             'Baglan'), 
            (4, 
             'Berat'), 
            (5, 
             'Burrel'), 
            (6, 
             'Durres'), 
            (7, 
             'Algiers'), 
            (8, 
             'Amsthas'), 
            (9, 
             'Aboucha'), 
            (10, 
             'Canillo'), 
            (11, 
             'Ordino'), 
            (12, 
             'Hobart'), 
            (13, 
             'Melbourne'), 
            (14, 
             'Eisenstadt'), 
            (47, 
             'Anchorage'), 
            (47, 
             'Fairbanks'), 
            (47, 
             'College'), 
            (47, 
             'Kodiak'), 
            (47, 
             'Meadow Lakes'), 
            (48, 
             'Houston'), 
            (48, 
             'Dallas'), 
            (48, 
             'Austin') 

DBCC checkident (city, reseed, 23) 

INSERT INTO city 
VALUES      (48, 
             'Fort Worth'), 
            (49, 
             'New York'), 
            (49, 
             'Buffalo'), 
            (49, 
             'Rochester'), 
            (49, 
             'Syracuse'), 
            (49, 
             'Albany'), 
            (50, 
             'Los Angeles'), 
            (50, 
             'San Diego'), 
            (50, 
             'San Francisco'), 
            (50, 
             'Oakland'), 
            (50, 
             'Sacremento'), 
            (55, 
             'Newark'); 

INSERT INTO designation 
VALUES      ('Project Manager', 
             'Project Manager'), 
            ('Software Developer', 
             'Software Developer'), 
            ('Team Leader', 
             'Team Leader'), 
            ('Business Analyst', 
             'Business Analyst'), 
            ('Design Engineer', 
             'Design Engineer'), 
            ('Tech Lead', 
             'Tech Lead'); 

/* Use Bulk Insert to import from .txt file */ 
DBCC checkident (employee_details, reseed, 0) 

BULK INSERT employee_details 
  FROM 'E:\Columbia Study\itelize\Project\Employee Details.txt' 
  WITH 
    ( 
      firstrow = 2, 
      lastrow = 7 
    ) 
DBCC checkident (employee_details, reseed, 10001) 

BULK INSERT employee_details 
  FROM 'E:\Columbia Study\itelize\Project\Employee Details.txt' 
  WITH 
    ( 
      firstrow = 8, 
      lastrow = 8 
    ) 
BULK INSERT salary 
  FROM 'E:\Columbia Study\itelize\Project\Employee Details.txt' 
  WITH 
    ( 
      firstrow = 12, 
      lastrow = 27 
    ) 
SELECT * 
FROM   salary 